### ISSUE TITLE
Using this Repo for Core i5

### ISSUE THREAD

**Issue by rajolm** [rsdev69/Lenovo-E560-Clover#14]
Hi @rsdev69 
I noticed that you did changes to CPU frequency in the last commits and I want to ask if this will effect me as my laptop have Core i5 CPU?
here is the specs of my CPU:

![image](https://user-images.githubusercontent.com/61861362/76697899-59c5e580-66a5-11ea-9d8f-d00147a4e465.png)

Notice how Max Turbo Frequency and TPD have differences from you Core i3 CPU specs:
 
![image](https://user-images.githubusercontent.com/61861362/76697920-8d087480-66a5-11ea-81eb-392d2cb3a40b.png)

Do I have to change anything to use your Repo for my laptop?

also I asked this question in another issue and I will be glade if you answer me:

> I remember that you said you will create a new Repo for your OpenCore configuration, can you please tell me when you will do that?
> also does the Trackpad gestures work for you? (like two fingure scroll and four fingers to show all apps)
> the Trackpad gestures doesn't work for me :(

**Comment by rsdev69** [comment]
> Do I have to change anything to use your Repo for my laptop?
Hi @rajolm, you cpu have Turbo Boost and I do not know if it works correctly. 
My CPU simple, has only base frequency and work correct SpeedStep.
Try this [repo](https://github.com/tluck/Lenovo-T460-Clover). In that repo laptop with Core i5/i7 
OpenCore i don't want to do. For me, no sense to do it, since everything works correctly.
Trackpad in laptop ELAN, right kext for Mojave and Catalina i do not know. Other kext work not correct. To emulate swipe, can be used SmartScroll app.
